
export const FETCH_DATA_START = 'FETCH_DATA_START'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED'


export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
export const FETCH_CART_START = 'FETCH_CART_START'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_FAILED = 'FETCH_CART_FAILED'
export const POST_CART_TO_DB = 'POST_CART_TO_DB'
export const POST_START = 'POST_START'
export const POST_SUCCESS = 'POST_SUCCESS'
export const POST_FAILED = 'POST_FAILED'



export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCES'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT= 'AUTH_LOGOUT'
export const CLEAR_AUTH_STATE= 'CLEAR_AUTH_STATE'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const UPDATE_START = 'UPDATE_START'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATE_FAILED'


export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const HIDE_CARTPREV = 'HIDE_CARTPREV'
export const SHOW_CARTPREV = 'SHOW_CARTPREV'


export const SIZE_SELECTED = 'SIZE_SELECTED'

